### ISSUE TITLE
Output escaping

### ISSUE THREAD

**Issue by boonebgorges** [scholarpress/scholarpress-coins#2]
User-generated data should be escaped as necessary. I see the following places where this ought to happen:
- `esc_attr()` for data put into the 'value' attributes of the meta box `input` elements
- `esc_attr()` for data being put into the Z3988 `title` attribute. I know you're running through `urlencode()`, which is good, but not enough. (This is a security issue with the existing plugin.)

**Comment by rjbaniel** [comment]
Second point is addressed here: https://github.com/scholarpress/scholarpress-coins/commit/04040e1b8ded1aafa9c378a9804f96fc5a0ef8bd

First point seems to have been addressed in some other commits.
