### ISSUE TITLE
Use a utility function rather than `$coins_postmeta_keys` global variable

### ISSUE THREAD

**Issue by boonebgorges** [scholarpress/scholarpress-coins#3]
Global variables are subject to namespace conflicts, mutability, and other icky nonsense. Create a wrapper function like `scholarpress_coins_keys()` and use that instead.

**Comment by rjbaniel** [comment]
Oh that's a good call - thank you. How's this? https://github.com/scholarpress/scholarpress-coins/commit/d0f641e77ee3440b11cd0ae2243aa88a76570faa

**Comment by boonebgorges** [comment]
Yup, exactly. Thanks!
