### ISSUE TITLE
Save routine improvements

### ISSUE THREAD

**Issue by boonebgorges** [scholarpress/scholarpress-coins#4]
In `scholarpress_coins_save_metadata()`, the following suggestions:
- loop through known keys rather than all of `$_POST`, which could be huge
- WP runs `$_POST` values through `addslashes()` (it's a long story) so you should always do eg `update_post_meta( $post_id, $key, wp_unslash( $_POST['key'] ) )`

**Comment by rjbaniel** [comment]
Thanks for that! How's this? https://github.com/scholarpress/scholarpress-coins/commit/800a07be24a2ae42903c9266cd409cf74129f430

**Comment by boonebgorges** [comment]
Looks good, except you don't need to unslash the key, because it comes from your hardcoded whiteliste.
