### ISSUE TITLE
php Fatal error 

### ISSUE THREAD

**Issue by rsanc77** [scholarpress/scholarpress-coins#6]
Wordpress version: 4.7.4
php version 5.6.30
 Can't use function return value in write context in /websites/journalofdh/www/wp-content/plugins/scholarpress-coins/scholarpress-coins.php on line 190

fix:
190: $postMeta = update_post_meta( $post_id, $key, $_POST[$key] );
191: if ( empty($postMeta) && ! empty( $legacy_data[$key] ) && legacy_data[$key] != 'scholarpress_coins_empty' ) {

**Comment by rjbaniel** [comment]
I'm very sorry for the long long delay here, @rsanc77. I believe I've addressed the problem with this commit: https://github.com/scholarpress/scholarpress-coins/commit/3d721a8bcb87e6f05ed18aa0db9aa4c639c2b3a9

Thank you for bringing it to my attention!
